# Generated by Django 3.0.8 on 2020-08-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=100)),
                ('publishing_house', models.CharField(max_length=100)),
            ],
        ),
    ]
